services:
  sg_osrm:
    image: osrm/osrm-backend
    hostname: osrm
    volumes:
      - ~/Documents/osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/singapore.osm.pbf && 
      osrm-partition /data/singapore.osrm && 
      osrm-customize /data/singapore.osrm && 
      osrm-routed --algorithm mld /data/singapore.osrm
      "

  strava_osrm:
    image: osrm/osrm-backend
    volumes:
      - ./osm:/osm
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 8000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -l INFO -p /profiles/foot.lua /osm/strava.osm
      && osrm-partition -l INFO /osm/strava.osrm
      && osrm-customize -l INFO /osm/strava.osrm
      && osrm-routed -l INFO --algorithm mld /osm/strava.osrm
      "  

networks:
  default:
    driver: bridge

volumes:
  pgadmin-data: